RFID.Admin/RFID.Admin/Models/AccountViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RFID.Admin.Models
{
    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class ExternalLoginListViewModel
    {
        public string ReturnUrl { get; set; }
    }

    public class SendCodeViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
        public string ReturnUrl { get; set; }
        public bool RememberMe { get; set; }
    }

    public class VerifyCodeViewModel
    {
        [Required]
        public string Provider { get; set; }

        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }
        public string ReturnUrl { get; set; }

        [Display(Name = "Remember this browser?")]
        public bool RememberBrowser { get; set; }

        public bool RememberMe { get; set; }
    }

    public class ForgotViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        public string Code { get; set; }
    }

    public class ForgotPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

RFID.Admin/RFID.Admin/Controllers/AccountController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using RFID.Admin.Models;
using RFID.Admin.Common;
using RFID.Admin.Security;

namespace RFID.Admin.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        private IMembershipService _membershipService = new AccountMembershipService();
        public AccountController()
        {
        }

        public AccountController(ApplicationUserManager userManager, ApplicationSignInManager signInManager )
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set 
            { 
                _signInManager = value; 
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Account/Login
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (returnUrl == "/Account/LogOut")
                returnUrl = null;
            // This doesn't count login failures towards account lockout
            // To enable password failures to trigger account lockout, change to shouldLockout: true
            EnumUserPortalAuthenticationStatus retVal = _membershipService.ValidateAdmin(model.Email, model.Password);
            GlobalModel global = new GlobalModel();
            switch (retVal)
            {
                case EnumUserPortalAuthenticationStatus.Successful:
                    return RedirectToLocal(returnUrl);
                case EnumUserPortalAuthenticationStatus.UnauthorizedLogin:
                    ModelState.AddModelError("", "Unauthorized Login");
                    return View(model);

                default:
                    ModelState.AddModelError("", "Invalid login attempt.");
                    return View(model);
            }
        }

        //
        // GET: /Account/VerifyCode
        [AllowAnonymous]
        public async Task<ActionResult> VerifyCode(string provider, string returnUrl, bool rememberMe)
        {
            // Require that the user has already logged in via username/password or external login
            if (!await SignInManager.HasBeenVerifiedAsync())
            {
                return View("Error");
            }
            return View(new VerifyCodeViewModel { Provider = provider, ReturnUrl = returnUrl, RememberMe = rememberMe });
        }

        //
        // POST: /Account/VerifyCode
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> VerifyCode(VerifyCodeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // The following code protects for brute force attacks against the two factor codes. 
            // If a user enters incorrect codes for a specified amount of time then the user account 
            // will be locked out for a specified amount of time. 
            // You can configure the account lockout settings in IdentityConfig
            var result = await SignInManager.TwoFactorSignInAsync(model.Provider, model.Code, isPersistent:  model.RememberMe, rememberBrowser: model.RememberBrowser);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(model.ReturnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid code.");
                    return View(model);
            }
        }

        //
        // GET: /Account/Register
        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await SignInManager.SignInAsync(user, isPersistent:false, rememberBrowser:false);
                    
                    // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return RedirectToAction("Index", "Home");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/ConfirmEmail
        [AllowAnonymous]
        public async Task<ActionResult> ConfirmEmail(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return View("Error");
            }
            var result = await UserManager.ConfirmEmailAsync(userId, code);
            return View(result.Succeeded ? "ConfirmEmail" : "Error");
        }

        //
        // GET: /Account/ForgotPassword
        [AllowAnonymous]
        public ActionResult ForgotPassword()
        {
            return View();
        }

        //
        // POST: /Account/ForgotPassword
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ForgotPassword(ForgotPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByNameAsync(model.Email);
                if (user == null || !(await UserManager.IsEmailConfirmedAsync(user.Id)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return View("ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                // Send an email with this link
                // string code = await UserManager.GeneratePasswordResetTokenAsync(user.Id);
                // var callbackUrl = Url.Action("ResetPassword", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);		
                // await UserManager.SendEmailAsync(user.Id, "Reset Password", "Please reset your password by clicking <a href=\"" + callbackUrl + "\">here</a>");
                // return RedirectToAction("ForgotPasswordConfirmation", "Account");
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/ForgotPasswordConfirmation
        [AllowAnonymous]
        public ActionResult ForgotPasswordConfirmation()
        {
            return View();
        }
        [AllowAnonymous]
        public ActionResult LogOut()
        {
            Session.Abandon();
            Response.Cookies.Clear();
            Response.Cookies.Add(new HttpCookie("ASP.NET_SessionId", ""));
            return RedirectToAction("Login", "Account");
        }
        //
        // GET: /Account/ResetPassword
        [AllowAnonymous]
        public ActionResult ResetPassword(string code)
        {
            return code == null ? View("Error") : View();
        }

        //
        // POST: /Account/ResetPassword
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ResetPassword(ResetPasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var user = await UserManager.FindByNameAsync(model.Email);
            if (user == null)
            {
                // Don't reveal that the user does not exist
                return RedirectToAction("ResetPasswordConfirmation", "Account");
            }
            var result = await UserManager.ResetPasswordAsync(user.Id, model.Code, model.Password);
            if (result.Succeeded)
            {

RFID.Admin/RFID.Admin/Controllers/GateTerminalController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using RFID.Admin.Models;
using RFID.Admin.Common;
using RFID.Admin.Security;
using System.Collections.Generic;
using RFID.Admin.BLL;
using RFIDAdmin.BLL.GateTerminalsService;
using System.Text.RegularExpressions;

namespace RFID.Admin.Controllers
{
    public class GateTerminalController : Controller
    {
        // GET: GateTerminal
        GlobalModel global = new GlobalModel();
        public ActionResult Index(Guid AccountID)
        {
            ViewBag.AccountID = AccountID;
            ViewBag.user = global;
            return View();
        }
        public ActionResult List(Guid AccountID,string Search,int PageIndex, int PageSize)
        {
            string Count = "";
            string roleid = null;

            GateTerminalBLL EmployeeBLL = new GateTerminalBLL();
            GateTerminalListEntityDC data = new GateTerminalListEntityDC();
            data = EmployeeBLL.GetAllGateTerminalByAccountID(AccountID,Search,PageIndex,PageSize);
            Dictionary<string, object> retData = new Dictionary<string, object>();

            retData.Add("data", data);
            retData.Add("total", Count);

            return Json(retData, JsonRequestBehavior.AllowGet);
        }
        public ActionResult SaveGateTerminal(GateTerminalModel model)
        {
            ViewBag.user = global;
            //    try
            //   {

            string id = model.GateTerminal.GateTerminalID.ToString();
            var result = Regex.Replace(id, @"{}", string.Empty);
            //    Guid AcctID = result.ToString();
            GateTerminalBLL GateTerminalBLL = new GateTerminalBLL();
            GateTerminalEntityDC data = new GateTerminalEntityDC();



            data.GateTerminalID = result.ToGuid();
            data.GateTerminalName = model.GateTerminal.GateTerminalName;
            data.AccountID = model.GateTerminal.AccountID;
            data.GateTypeID = model.GateTerminal.GateTypeID;
            data.IsActive = model.GateTerminal.IsActive;
            data.CreatedBy = global.GlobalUserName;

            return Json(GateTerminalBLL.SaveGateTerminal(data), JsonRequestBehavior.AllowGet);

        }

        public ActionResult GetAllGateType()
        {
            string Count = "";
            string roleid = null;

            GateTerminalBLL EmployeeBLL = new GateTerminalBLL();
            GateTypeListEntityDC data = new GateTypeListEntityDC();
            data = EmployeeBLL.GetAllGateType();
            Dictionary<string, object> retData = new Dictionary<string, object>();

            retData.Add("data", data);
            retData.Add("total", Count);

            return Json(retData, JsonRequestBehavior.AllowGet);
        }
        public ActionResult SaveEmployee(GateTerminalModel model)
        {
            GateTerminalBLL EmployeeBLL = new GateTerminalBLL();
            GateTerminalEntityDC data = new GateTerminalEntityDC()
            {
                GateTerminalID = model.GateTerminal.GateTerminalID,
                GateTerminalName = model.GateTerminal.GateTerminalName,
                IsActive = model.GateTerminal.IsActive,
                CreatedBy = model.GateTerminal.CreatedBy,
            };
            return Json(EmployeeBLL.SaveGateTerminal(data), JsonRequestBehavior.AllowGet);
        }
    }
}

RFID.Admin/RFID.Admin/Views/Company/Partial/Account.cshtml
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <div class="row clearfix action-group" ng-if="mode=='list'  && !processing.enable">
                    <div class="col-md-2">
                        <h2>Company</h2>
                    </div>
                    <div class="col-md-2" style="height:50px;padding-top:15px;">
                        <div class="button-demo pull-right">
                            <button type="button" class="btn bg-red btn-circle waves-effect waves-circle waves-float" ng-click="ToAdd()">
                                <i class="material-icons">plus_one</i>
                            </button>
                        </div>
                    </div>
                    <div class="col-md-4" style="height:50px;padding-top:15px;">
                        <div class="button-demo pull-right">
                            <md-fab-actions class="md-toolbar-tools" style="height:30px;">
                                <md-button aria-label="photo" class="md-icon-button" ng-click="ConfirmDelete()" ng-if="mode=='list' && checklistary.length > 0">
                                    <md-tooltip md-direction="top">Delete company</md-tooltip>
                                    <i class="material-icons">delete</i>
                                </md-button>
                            </md-fab-actions>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div layout-gt-sm="row" style="height:50px">
                            <md-input-container class="md-block" flex-gt-sm>
                                <label>Search</label>
                                <input ng-keyup="Search()" ng-model="list.Search" autocomplete="off">
                            </md-input-container>
                        </div>
                    </div>

                </div>
                <div class="row clearfix action-group" ng-if="mode!='list'  && !processing.enable">
                    <div class="col-md-4">
                        <!--<h2>{{ (mode=='Account') ? 'Account' : 'Account' ? 'Department' : 'Department' ? 'Affilation' : 'Affilation' ? 'GateTerminal' : 'GateTerminal' }}</h2>-->
                    </div>
                </div>
                <div class="clearfix action-group" ng-if="processing.enable">
                    <h2 ng-if="processing.label == 'delete'"><i class="material-icons" style="vertical-align:-5px;">delete</i> Deleting company {{ checkindex }} of {{ checklistary.length }}</h2>
                </div>
            </div>
            <div class="body">

                <div ng-if="mode=='list'">
                    <!---  <a aria-label="photo" class="md-icon-button" ng-click="ToAdd()">
                              <md-tooltip md-direction="top">Edit detail</md-tooltip>
                              <i class="material-icons">edit</i>
                          </a>-->

                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover js-basic-example dataTable" style="font-size:12.5px;">
                            <thead>
                                <tr>
                                    <th>
                                        <center>
                                            <md-checkbox ng-model="checkAll" aria-label="select" class="md-warn"></md-checkbox>
                                        </center>
                                    </th>
                                    <th>Company Name</th>
                                    <th>Address</th>
                                    <th>MobileNumber</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr ng-repeat="item in list.data.AccountList" ng-if="!loading">
                                    <td>
                                        <center>
                                            <md-checkbox ng-model="checklist[item.AccountID]" ng-true-value="'{{ item.AccountID }}'" ng-false-value="{{null}}" aria-label="select" ng-change="checkchanged()" class="md-warn" ng-checked="checkAll"></md-checkbox>
                                        </center>
                                    </td>
                                    <td class="noright">
                                        {{item.AccountName}}
                                    </td>
                                    <td>
                                        {{item.Branch}}
                                    </td>
                                    <td>{{ item.EmailAddress }}</td>
                                    <td>

                                        <a aria-label="photo" class="md-icon-button" ng-click="ToAccountForm(item)">
                                            <md-tooltip md-direction="top">Edit detail</md-tooltip>
                                            <i class="material-icons">edit</i>
                                        </a>
                                        &nbsp;||                                            &nbsp;
                                        <a aria-label="photo" class="md-icon-button" href="@Url.Action("Index","GateTerminal")?AccountID={{item.AccountID}}">
                                            <md-tooltip md-direction="top">Gate Terminal</md-tooltip>
                                            <i class="material-icons">remove_red_eye</i>
                                        </a>

                                    </td>
                                </tr>
                                <tr ng-if="list.data.length == 0 && list.Search != '' && !list.loading">
                                    <td colspan="5">
                                        <i class="material-icons">info</i>
                                        <span style="vertical-align: super;">No matching "{{ list.Search }}" company were found.</span>

                                    </td>
                                </tr>

                                <tr ng-if="list.data.length == 0  && list.Search == '' && !list.loading">
                                    <td colspan="5">
                                        <i class="material-icons">info</i>
                                        <span style="vertical-align: super;">No company yet.</span>

                                    </td>
                                </tr>
                                <tr ng-if="list.loading">
                                    <td colspan="5">
                                        <i class="material-icons">info</i>
                                        <span style="vertical-align: super;">Loading data...</span>

                                    </td>
                                </tr>


                            </tbody>
                        </table>
                    </div>
                    <div class="dataTables_paginate paging_simple_numbers" align="center" id="DataTables_Table_0_paginate">
                        <ul class="pagination">
                            <li class="paginate_button previous" id="DataTables_Table_0_previous">
                                <a aria-controls="DataTables_Table_0" ng-click="PageIndexChange(-1)" ng-disabled="(list.totalPage == 0)" tabindex="0">Previous</a>
                            </li>
                            <li class="paginate_button">
                                <a aria-controls="DataTables_Table_0" tabindex="0">{{ (list.totalPage > 0) ? list.PageIndex : 0 }} of {{ list.totalPage }} - {{ list.total }} item(s)</a>
                            </li>
                            <li class="paginate_button next" id="DataTables_Table_0_next">
                                <a aria-controls="DataTables_Table_0" ng-click="PageIndexChange(1)" ng-disabled="(list.totalPage == 0)" tabindex="0">Next</a>
                            </li>
                        </ul>
                    </div>
                </div>


                @*<div ng-if="mode=='GateTerminal' || mode=='GateTerminals'">
                        @Html.Partial("partial/GateTerminal")
                    </div>*@
            </div>
        </div>
    </div>
</div>

RFID.Admin/RFID.Admin/Views/Company/Partial/AccountForm.cshtml
<form class="form-horizontal" id="form">
    <div class="row">
        <div class="col-md-12">
            <input type="text" hidden name="Account.AccountID" ng-model="Employee.AccountID" />
            <div layout-gt-sm="row">
                <md-input-container class="md-block" flex-gt-sm>
                    <label>Account Name</label>
                    <input ng-model="Employee.AccountName" name="Account.AccountName" autocomplete="off">
                </md-input-container>
                <md-input-container class="md-block" flex-gt-sm>
                    <label>Branch</label>
                    <input ng-model="Employee.Branch" name="Account.Branch" autocomplete="off">
                </md-input-container>
                <md-input-container class="md-block" flex-gt-sm>
                    <label>Address</label>
                    <input ng-model="Employee.Address" name="Account.Address" autocomplete="off">
                </md-input-container>
            </div>
            <div layout-gt-sm="row">
                <md-input-container class="md-block" flex-gt-sm>
                    <label>Email Address</label>
                    <input ng-model="Employee.EmailAddress" name="Account.EmailAddress" type="email" autocomplete="off">
                </md-input-container>
                <md-input-container class="md-block" flex-gt-sm>
                    <label>Telephone Number</label>
                    <input ng-model="Employee.TelephoneNumber" name="Account.MobileNo" autocomplete="off">
                </md-input-container>

            </div>


            <div layout-gt-sm="row">
                <md-input-container class="md-block" flex-gt-sm>
                    <label>Mobile Number:</label>
                    <input ng-model="Employee.MobileNumber" name="Account.MobileNumber" autocomplete="off">
                </md-input-container>
            </div>

            <div layout-gt-sm="row">
                <div class="col-md-8">
                    <div class="button-demo pull-right">
                        <button type="button" ng-click="ToCancel()" class="btn btn-default waves-effect">CANCEL</button>
                        <button type="button" ng-click="ConfirmSave()" class="btn btn-danger waves-effect">SAVE</button>
                    </div>
                </div>

            </div>
            </div>

    </div>



</form>

RFID.Admin/RFID.Admin/Views/Company/Partial/Department.cshtml
<div class="row clearfix">

    <!-- #END# Task Info -->
    <!-- Browser Usage -->
    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    <i class="material-icons">timelapse</i>
                    <span>Recent Time Log</span>
                </h2>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-striped" style="font-size:12.5px;">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>RFID</th>
                                <th>GateTerminalName</th>
                                <th>Log Type</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="item in data" ng-if="!loading">
                                <td class="noright">
                                    {{item.FirstName}} {{item.LastName}}
                                </td>
                                <td>
                                    {{item.RFID}}
                                </td>
                                <td>{{ item.GateTerminalName }}</td>
                                <td>
                                    {{item.LogType}}
                                </td>
                            </tr>
                            <tr ng-if="attendance.length == 0 && !loading">
                                <td colspan="4">No Attendance Log yet.</td>
                            </tr>
                            <tr ng-if="loading">
                                <td colspan="4">Loading...</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

    <div class="col-lg-6 col-md-3 col-sm-12 col-xs-12">
        <md-list>
            <md-subheader class="md-no-sticky" style="background: #F44336;color: white;"><i class="material-icons">exit_to_app</i> <span>Recent Leave</span></md-subheader>
            <md-list-item class="noright" ng-repeat="item in leaves" ng-if="!loading">
                <img ng-if="item.ProfilePhoto" ng-src="{{item.ProfilePhoto}}" onerror="this.src='/Images/no-avatar.jpg'" class="md-avatar" style="object-fit: cover;" />
                <img ng-if="!item.ProfilePhoto" src="~/Images/no-avatar.jpg" class="md-avatar" style="object-fit: cover;" />
                <p>{{ item.FirstName }} {{ item.LastName }}</p>
                <span style="position: absolute;margin-top: 15px;font-size: 10px;left: 73px;">{{ item.LeaveStartDate  | amDateFormat:'MMM D,YYYY'}} to {{ item.LeaveEndDate  | amDateFormat:'MMM D,YYYY'}} - {{item.NoOfDays}} day(s)</span>
            </md-list-item>
            <md-list-item class="noright" ng-if="leaves.length == 0 && !loading">
                No Leave yet
            </md-list-item>

            <md-list-item class="noright" ng-if="loading">
                Loading...
            </md-list-item>

        </md-list>
    </div>
</div>